create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'installer' check (role in ('admin','installer')),
  created_at timestamptz not null default now()
);

create table if not exists businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  google_review_url text not null,
  logo_url text,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE')),
  created_at timestamptz not null default now()
);

create table if not exists cards (
  id uuid primary key default gen_random_uuid(),
  serial text unique not null,
  setup_token text unique,
  status text not null default 'UNASSIGNED' check (status in ('UNASSIGNED','ACTIVE','INACTIVE','LOST','REPLACED')),
  business_id uuid references businesses(id) on delete set null,
  activated_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  card_id uuid not null references cards(id) on delete cascade,
  method text not null default 'unknown' check (method in ('nfc','qr','unknown')),
  user_agent text,
  referer text,
  created_at timestamptz not null default now()
);

create index if not exists cards_serial_idx on cards(serial);
create index if not exists events_card_idx on events(card_id);
create index if not exists events_created_idx on events(created_at);

alter table profiles enable row level security;
alter table businesses enable row level security;
alter table cards enable row level security;
alter table events enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from profiles where id=auth.uid() and role='admin') $$;

create policy "admin profiles" on profiles for select using (id=auth.uid() or public.is_admin());
create policy "admin businesses" on businesses for all using (public.is_admin()) with check (public.is_admin());
create policy "admin cards" on cards for all using (public.is_admin()) with check (public.is_admin());
create policy "admin events" on events for select using (public.is_admin());

-- Setelah membuat user di Authentication, masukkan:
-- insert into profiles(id,full_name,role) values ('UUID_USER','Admin','admin');
